version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Replace with your root password
      MYSQL_DATABASE: mydatabase         # Replace with your desired database name
      MYSQL_USER: myuser                 # Optional, a user for non-root operations
      MYSQL_PASSWORD: mypassword         # Optional, password for the above user
    ports:
      - "3307:3306"  # Expose MySQL on port 3307
    volumes:
      - mysql_data:/var/lib/mysql  # Persist data

  # Spring Boot application service
  app:
    build: .  # Assuming your Dockerfile is in the current directory
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/quiz-kids?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC  # Connection URL
      SPRING_DATASOURCE_USERNAME: myuser                         # Replace with your MySQL user
      SPRING_DATASOURCE_PASSWORD: mypassword                     # Replace with your MySQL password
    ports:
      - "8080:8080"  # Expose the Spring Boot app on port 8080
    depends_on:
      - mysql  # Ensure MySQL starts before the app
    volumes:
      - app_logs:/app/logs  # This volume persists application logs

volumes:
  # Declare named volumes here
  mysql_data:  # This volume persists MySQL data
  app_logs:  # This volume persists application logs
