version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"  # Expose MySQL on port 3307
    volumes:
      - mysql_data:/var/lib/mysql

  # Spring Boot application service
  app:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydatabase?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC  # Connection URL
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      ADMIN_PASSWORD: 12345 # Reads from .env
      REMEMBER_ME_KEY: remeberMeKey
    ports:
      - "8080:8080"  # Expose the Spring Boot app on port 8080
    depends_on:
      - mysql  # Ensure MySQL starts before the app
    volumes:
      - app_logs:/app/logs  # This volume persists application logs

volumes:

  mysql_data:
  app_logs:
