spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/quiz-kids?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: ${db_username}
    password: ${db_password}
  sql:
    init:
      mode: never
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    database-platform: org.hibernate.dialect.MySQLDialect
    #For MySQL 5
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    check-template-location: off
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0
  devtools:
    restart:
      additional-paths: src/main/resources/templates
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:
binding-result-package: org.springframework.validation.BindingResult
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: TRACE
#    org.springframework.security: TRACE


#Admin password
app:
  admin:
    password: ${ADMIN_PASSWORD}
  remember.me.key: ${REMEMBER_ME_KEY}
